export const metadata = {
  title: 'Terms of Service — Operator AI',
  description: 'Terms governing your use of Operator AI.',
};

export default function TermsPage() {
  const updated = 'April 15, 2026';
  return (
    <div className="min-h-screen bg-bg">
      <div className="max-w-[780px] mx-auto px-6 py-16 lg:py-24">
        <div className="text-[11px] uppercase tracking-[0.18em] text-gold mb-2">Legal</div>
        <h1 className="font-display text-[36px] lg:text-[44px] leading-tight mb-2">Terms of Service</h1>
        <p className="text-[13px] text-fg-muted mb-10">Last updated: {updated}</p>

        <div className="prose-gold space-y-8 text-[14.5px] text-fg-soft leading-relaxed">
          <section>
            <h2 className="font-display text-[20px] text-fg mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using Operator AI (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service.</p>
          </section>

          <section>
            <h2 className="font-display text-[20px] text-fg mb-3">2. Description of Service</h2>
            <p>Operator AI is an AI-powered business platform that provides: AI chat with multiple language models; AI image and video generation; voice interaction capabilities; workflow automation; document analysis; third-party integrations. The Service is provided on a subscription basis with multiple plan tiers.</p>
          </section>

          <section>
            <h2 className="font-display text-[20px] text-fg mb-3">3. Account Registration</h2>
            <p>To use the Service, you must create an account with a valid email address. You are responsible for maintaining the confidentiality of your account credentials. You must be at least 16 years old to use the Service. You are responsible for all activities under your account.</p>
          </section>

          <section>
            <h2 className="font-display text-[20px] text-fg mb-3">4. Subscription and Billing</h2>
            <p>The Service offers free trials and paid subscription plans. Paid plans are billed monthly through Stripe. You can cancel your subscription at any time; access continues until the end of the current billing period. Refunds are handled on a case-by-case basis within 14 days of purchase. We reserve the right to change pricing with 30 days&apos; notice.</p>
          </section>

          <section>
            <h2 className="font-display text-[20px] text-fg mb-3">5. Acceptable Use</h2>
            <p>You agree not to: use the Service for any illegal purpose; generate content that violates the rights of others; attempt to reverse-engineer, hack, or compromise the Service; use automated systems to access the Service beyond normal usage; resell or redistribute the Service without authorization; generate harmful, abusive, or deceptive content.</p>
          </section>

          <section>
            <h2 className="font-display text-[20px] text-fg mb-3">6. AI-Generated Content</h2>
            <p>Content generated by AI models (text, images, videos) through the Service is provided &quot;as is&quot;. You retain ownership of prompts you provide. For generated content, you receive a non-exclusive license to use it for personal and commercial purposes, subject to the underlying AI provider terms. We do not guarantee the accuracy, completeness, or appropriateness of AI-generated content. You are responsible for reviewing and verifying AI-generated content before use.</p>
          </section>

          <section>
            <h2 className="font-display text-[20px] text-fg mb-3">7. Your Content</h2>
            <p>You retain all rights to content you upload to the Service (documents, images, data). By uploading content, you grant us a limited license to process it for providing the Service. We do not sell or share your content with third parties except as needed to operate the Service (e.g., sending documents to AI models for analysis).</p>
          </section>

          <section>
            <h2 className="font-display text-[20px] text-fg mb-3">8. Intellectual Property</h2>
            <p>The Service, including its design, code, and branding, is owned by Operator AI. The Operator AI name, logo, and visual identity are our trademarks. You may not copy, modify, or distribute the Service without permission.</p>
          </section>

          <section>
            <h2 className="font-display text-[20px] text-fg mb-3">9. Limitation of Liability</h2>
            <p>THE SERVICE IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTIES OF ANY KIND. WE ARE NOT LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES. OUR TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT YOU PAID IN THE LAST 12 MONTHS. We are not responsible for outages, data loss due to third-party service failures, or AI model availability changes.</p>
          </section>

          <section>
            <h2 className="font-display text-[20px] text-fg mb-3">10. Termination</h2>
            <p>We may suspend or terminate your account for violation of these terms. You may delete your account at any time. Upon termination, your data will be deleted per our Privacy Policy.</p>
          </section>

          <section>
            <h2 className="font-display text-[20px] text-fg mb-3">11. Changes to Terms</h2>
            <p>We may modify these Terms at any time. Material changes will be communicated via email or in-app notification at least 30 days in advance. Continued use after changes constitutes acceptance.</p>
          </section>

          <section>
            <h2 className="font-display text-[20px] text-fg mb-3">12. Governing Law</h2>
            <p>These Terms are governed by the laws of the European Union and the Kingdom of Spain. Any disputes shall be resolved in the courts of Spain.</p>
          </section>

          <section>
            <h2 className="font-display text-[20px] text-fg mb-3">13. Contact</h2>
            <p>For questions about these Terms, contact us at <a href="mailto:legal@operatoraiapp.com" className="text-gold hover:underline">legal@operatoraiapp.com</a>.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
